Migrate to GitHub actions
stackbuilders/atomic-write pull request #31
Opened 2023-03-31 20:59 UTC by Alex0jk

Add basic setup for GitHub actions : `release.yml` and `build.yml`
Removed the `travis.yml` file
Updated the .`gitignore` file

This is for #30

2023-04-21 18:27 UTC, sestrella reviewed
@Alex0jk nice job so far! I would just suggest updating the status badges on the README file and also adding a section talking about the release process, if I understand this workflow correctly a maintainer would need to create a GH release before publishing a new version to Hackage. Am I right?

2023-08-22 13:34 UTC, CristhianMotoche requested changes
@Alex0jk Looks good. Although, we don't have an executable on atomic-write so we don't need many of the steps that you defined in the `draft.yml` file. Also, can you give a look at the `README.md`? It seems the diagram is not rendering correctly. Thanks!

2023-08-22 13:34 UTC, CristhianMotoche commented on .github/workflows/README.md
> +```
@Alex0jk It seems this diagram has some kind of error. It cannot be rendered. Can you double check that please?

2023-08-22 13:34 UTC, CristhianMotoche commented on .github/workflows/draft.yml
> +        run: sudo chown $USER:$USER atomic-write
@Alex0jk atomic-write doesn't provide an executable. It's just a [library](https://github.com/stackbuilders/atomic-write/blob/master/atomic-write.cabal#L52). We don't need any step related to uploading a binary to a GH release.

2023-08-28 22:48 UTC, CristhianMotoche approved these changes
LGTM!

2023-08-29 13:21 UTC, merged